name: Export GitHub Custom Properties to Excel

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM UTC

jobs:
  export-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests pandas openpyxl

      - name: Run Export Script
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          MY_GITHUB_ORG: ${{ secrets.MY_GITHUB_ORG }}
        run: python scripts/export_custom_props.py

      - name: Commit and Push Excel Report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add github_custom_properties.xlsx
          git commit -m "📊 Update GitHub custom properties report" || echo "No changes to commit"
          git push
